# -*- coding: utf-8 -*-
"""DATA STORY TELLING APP_WEEK-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZFukgwAuWKlkj-eqaCYy5_dKp2NLh94
"""

!pip install plotly pandas -q

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import io
from plotly.subplots import make_subplots

url = "https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv"
gdp_df = pd.read_csv(url)

# Use Plotly built-in Gapminder (always works, no download needed)
df = px.data.gapminder()
df2007 = df[df['year'] == 2007].reset_index(drop=True)
df2007.rename(columns={
    'country': 'Country',
    'continent': 'Continent',
    'lifeExp': 'LifeExpectancy',
    'pop': 'Population',
    'gdpPercap': 'GDP'
}, inplace=True)
df

print("""
╔══════════════════════════════════════════════════════╗
║         GLOBAL DEVELOPMENT DATA STORY               ║
║    Exploring GDP, Life & Population (2007)          ║
╚══════════════════════════════════════════════════════╝
""")

print("✅ Dataset Loaded | Shape:", df2007.shape)
print(f"   Countries : {df2007['Country'].nunique()}")
print(f"   Continents: {df2007['Continent'].nunique()}")
print(df2007.head())

# ── EXPLORATORY DATA ANALYSIS ────────────────────────────────
print("\n========== STATISTICAL SUMMARY ==========")
print(df2007[['LifeExpectancy', 'Population', 'GDP']].describe().round(2))

print("\n========== MISSING VALUES ==========")
print(df2007.isnull().sum())

print("\n── Top 5 Countries by GDP ──")
print(df2007.nlargest(5, 'GDP')[['Country', 'Continent', 'GDP']].to_string(index=False))

print("\n── Bottom 5 Countries by Life Expectancy ──")
print(df2007.nsmallest(5, 'LifeExpectancy')[['Country', 'Continent', 'LifeExpectancy']].to_string(index=False))

# ── VISUALIZATION 1 : GDP vs Life Expectancy ─────────────────
fig1 = px.scatter(
    df2007,
    x='GDP', y='LifeExpectancy',
    size='Population',
    color='Continent',
    hover_name='Country',
    log_x=True,
    size_max=60,
    title='GDP per Capita vs Life Expectancy (2007)',
    labels={'GDP': 'GDP per Capita (log)', 'LifeExpectancy': 'Life Expectancy (yrs)'}
)
fig1.update_layout(legend_title='Continent')
fig1.show()

# ── VISUALIZATION 2 : Life Expectancy Trend Over Years ───────
df_trend = df[df['country'].isin(['India', 'China', 'United States', 'Brazil', 'Nigeria'])]
df_trend = df_trend.rename(columns={'country': 'Country', 'lifeExp': 'LifeExpectancy'})
fig2 = px.line(
    df_trend,
    x='year', y='LifeExpectancy',
    color='Country',
    markers=True,
    title='Life Expectancy Trend Over Years (Selected Countries)',
    labels={'year': 'Year', 'LifeExpectancy': 'Life Expectancy (yrs)'}
)
fig2.show()

# ── VISUALIZATION 3 : Population by Continent ────────────────
pop_cont = df2007.groupby('Continent')['Population'].sum().reset_index()
pop_cont['Population_M'] = (pop_cont['Population'] / 1e6).round(1)
fig3 = px.bar(
    pop_cont,
    x='Continent', y='Population_M',
    color='Continent',
    title='Total Population by Continent (2007, in Millions)',
    labels={'Population_M': 'Population (Millions)'},
    text='Population_M'
)
fig3.update_traces(textposition='outside')
fig3.show()

# ── VISUALIZATION 4 : GDP Distribution by Continent ──────────
fig4 = px.box(
    df2007,
    x='Continent', y='GDP',
    color='Continent',
    title='GDP per Capita Distribution by Continent (2007)',
    labels={'GDP': 'GDP per Capita ($)'},
    points='all'
)
fig4.show()

# ── VISUALIZATION 5 : World Map - Life Expectancy ────────────
fig5 = px.choropleth(
    df2007,
    locations='Country',
    locationmode='country names',
    color='LifeExpectancy',
    hover_name='Country',
    color_continuous_scale='RdYlGn',
    title='World Map - Life Expectancy by Country (2007)',
    labels={'LifeExpectancy': 'Life Expectancy'}
)
fig5.show()

# ── VISUALIZATION 6 : Correlation Heatmap ────────────────────
corr = df2007[['LifeExpectancy', 'Population', 'GDP']].corr().round(2)
fig6 = go.Figure(go.Heatmap(
    z=corr.values,
    x=corr.columns.tolist(),
    y=corr.columns.tolist(),
    colorscale='RdBu',
    zmid=0,
    text=corr.values,
    texttemplate='%{text}'
))
fig6.update_layout(title='Correlation Heatmap: GDP, Population & Life Expectancy')
fig6.show()

# ── INSIGHTS & CONCLUSION ────────────────────────────────────
print("""
╔══════════════════════════════════════════════════════╗
║                  KEY INSIGHTS                       ║
╠══════════════════════════════════════════════════════╣
║  • Higher GDP strongly links to longer life         ║
║  • Europe has the highest avg life expectancy       ║
║  • Africa has the lowest GDP & life expectancy      ║
║  • Asia holds the majority of world population      ║
║  • Americas show wide GDP inequality                ║
╠══════════════════════════════════════════════════════╣
║               RECOMMENDATIONS                       ║
╠══════════════════════════════════════════════════════╣
║  • Invest in healthcare in low GDP nations          ║
║  • Reduce income inequality within continents       ║
║  • Support economic growth in African countries     ║
╚══════════════════════════════════════════════════════╝
""")